### ISSUE TITLE
Missing mana-p emoji

### ISSUE THREAD

**Issue by Jesin** [scryfall/manamoji-slack#3]
The oracle text for [Rage Extractor](https://scryfall.com/card/nph/91/rage-extractor) contains `{P}`, which the Slack bot translates to `:mana-p:` when the other manamoji are installed. There is no corresponding file at `emojis/mana-p.png`.

**Comment by csuhta** [comment]
@Jesin Added, thanks for reporting!

**Comment by Jesin** [comment]
@csuhta Thanks. I suspect manamoji-discord may have a similar issue, though I do not use it myself.

**Comment by csuhta** [comment]
Just added that too https://github.com/scryfall/manamoji-discord/commit/b05ae63773cff9a024ec83cafe9d569780fb9206
